<?php

namespace App\Exceptions;

enum ErrorCode: string
{
    case UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case INVALID_TOKEN = 'INVALID_TOKEN';
    case FORBIDDEN = 'FORBIDDEN';
    case ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED';
    case INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD';
}
